export { MiscTab } from './MiscTab'
export { PersonalTab } from './PersonalTab'
export { default as Settings } from './Settings.vue'
export { default as Shortcuts } from './ShortcutsTab/Shortcuts.vue'
export { ValorantTab } from './ValorantTab'
