export { MiscTab } from './MiscTab'
export { PersonalTab } from './PersonalTab'
export { default as SettingsModal } from './SettingsModal.vue'
export { SpotifyTab } from './SpotifyTab'
export { ValorantTab } from './ValorantTab'
